### ISSUE TITLE
Error durring build

### ISSUE THREAD

**Issue by kenthinson** [rickyzhang82/tsocks_dnsdirect#2]
I'm getting a error during build on 10.15.2

```
checking for strcspn... no
configure: error: "Required function not found"
```

Any chance you can upload a binary to the releases tab of this github?

**Comment by rickyzhang82** [comment]
The latest Mac OS X drop supporting for 32bit. I fixed the build script. Check out 982f05e9f9e98582cfc1f2efed0c5bc7aec1196e from latest master branch. I can build it

**Comment by rickyzhang82** [comment]
I assume everything is OK now.
